name: Contribution Auto

on:
  schedule:
    - cron: '0 */12 * * *'  # Toutes les 12h (UTC)
  workflow_dispatch:        # Permet aussi de lancer à la main

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le repo
        uses: actions/checkout@v4

      - name: Modifier le fichier et pousser
        run: |
          echo "Ping automatique à $(date)" >> contrib-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add contrib-log.txt
          git commit -m "Contribution automatique - $(date)" || echo "Aucun changement à commit"
          git push
